# Generated by Django 6.0.3 on 2026-03-15 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='phone',
            field=models.CharField(max_length=250, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid UK mobile phone number.', regex='^(\\+44|0)7\\d{9}$')]),
        ),
    ]
